services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "4000:80"
    volumes:
      - ./frontend/views:/frontend/views
      - ./frontend/assets:/frontend/assets
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/backend
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./frontend/views:/frontend/views
      - ./frontend/assets:/frontend/assets
      - ./backend:/backend
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATA_BASE: ${MYSQL_DATA_BASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATA_BASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "4001:3306"
  
  mongo:
    image: mongo:7.0.16
    container_name: mongo
    volumes:
      - mongo-data:/data/dbdata
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MYSQL_DATA_BASE}
    ports:
      - "4002:27017"
    
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "8082:8081"

volumes:
  dbdata:
  mongo-data: